version: '3'
services:
  sharder-core:
    container_name: sharder
#    image: 'cos-testnet-0.0.9:latest'
    image: 'registry.cn-hangzhou.aliyuncs.com/sharder/cos:latest'
    volumes:
    - "~/sharder-docker/conf:/sharder/conf"
    - "~/sharder-docker/sharder_test_db:/sharder/sharder_test_db"
    - "~/sharder-docker/logs:/sharder/logs"
    - "~/sharder-docker/storage/ipfs/.ipfs:/sharder/storage/ipfs/.ipfs"
    ports:
    - "8215:8215"
    - "8218:8218"
    - "8001:8001"
    - "9001:9001"
    - "8099:8099"
